package ui;

import java.util.LinkedList;
import java.util.List;

import org.apache.commons.math3.analysis.function.Gaussian;
import org.apache.tools.ant.taskdefs.Javadoc.Html;

import generator.Parameter;
import others.StoryRecord;

/**
 *
 * @author liqimou
 */
public class OneCharacterStoryShowingWindow extends javax.swing.JFrame {

    /**
     * Creates new form StoryShowWindow
     */
    public OneCharacterStoryShowingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        totalScoreLabel = new javax.swing.JLabel();
        scoreTextField = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        lengthTextField = new javax.swing.JTextField();
        lengthScoreTextField = new javax.swing.JTextField();
        PNConstraintLabel = new javax.swing.JLabel();
        PNConstraintTextField = new javax.swing.JTextField();
        PNConstraintScoreTextField = new javax.swing.JTextField();
        locationConstraintScore = new javax.swing.JLabel();
        locationConstraintTextField = new javax.swing.JTextField();
        storySequenceLabel = new javax.swing.JLabel();
        storySequenceScrollPane = new javax.swing.JScrollPane();
        storySequenceTextArea = new javax.swing.JTextArea();
        quasiEnglishLabel = new javax.swing.JLabel();
        essayScrollPane = new javax.swing.JScrollPane();
        essayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Story");
        
        totalScoreLabel.setText("Total Score :");

        scoreTextField.setEditable(false);
        scoreTextField.setText(Parameter.decimalFormat.format(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getScore())+"");

        lengthLabel.setText("Length & Score :");
        
        lengthTextField.setEditable(false);
        lengthTextField.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory().size()+"");

        lengthScoreTextField.setEditable(false);
        Parameter.gaussianDistribution = new Gaussian(Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength, Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength / 3);
        lengthScoreTextField.setText(Parameter.decimalFormat.format(Parameter.lengthModel.getValue(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory().size(), Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength))+"");
        
        List <String> cList = new LinkedList<String>();
		for (StoryRecord k : Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory()) {
			cList.add(k.getConcept());
		}
        PNConstraintLabel.setText("P/N Constraint & Score :");

        PNConstraintTextField.setEditable(false);
        PNConstraintTextField.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.positiveConstraintString+"/"
        		+ Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.negativeConstraintString);
        
        PNConstraintScoreTextField.setEditable(false);
        PNConstraintScoreTextField.setText(Parameter.decimalFormat.format(Parameter.constraintModel.getValue(cList, Parameter.selectStoryIndex))+"");
        
        locationConstraintScore.setText("Location Constraint Score :");
        locationConstraintTextField.setEditable(false);
        
        locationConstraintTextField.setText("Location Constraint Score :");
        locationConstraintTextField.setText(Parameter.decimalFormat.format(Parameter.locationConstraintModel.getValue(cList))+"");
        
        storySequenceLabel.setText("Story Sequence");
        
        storySequenceTextArea.setEditable(false);
        storySequenceTextArea.setColumns(20);
        storySequenceTextArea.setLineWrap(true);
        storySequenceTextArea.setRows(5);
        storySequenceTextArea.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StorySequenceList.get(Parameter.selectStoryResultIndex));
        storySequenceScrollPane.setViewportView(storySequenceTextArea);

        quasiEnglishLabel.setText("Quasi-English Story");
        
        essayTextArea.setEditable(false);
        essayTextArea.setColumns(20);
        essayTextArea.setLineWrap(true);
        essayTextArea.setRows(5);
        essayTextArea.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).essayList.get(Parameter.selectStoryResultIndex));
        essayScrollPane.setViewportView(essayTextArea);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quasiEnglishLabel)
                .addGap(229, 229, 229))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(storySequenceLabel)
                .addGap(251, 251, 251))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storySequenceScrollPane)
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(essayScrollPane)
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalScoreLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PNConstraintLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(locationConstraintScore, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scoreTextField)
                            .addComponent(locationConstraintTextField)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PNConstraintTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(lengthTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PNConstraintScoreTextField)
                                    .addComponent(lengthScoreTextField)))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(titleLabel)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalScoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNConstraintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNConstraintLabel)
                    .addComponent(PNConstraintScoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationConstraintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationConstraintScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storySequenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storySequenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quasiEnglishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(essayScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                                       

    /**
     * @param args the command line arguments
     */
    public void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneCharacterStoryShowingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JLabel PNConstraintLabel;
    private javax.swing.JTextField PNConstraintScoreTextField;
    private javax.swing.JTextField PNConstraintTextField;
    private javax.swing.JLabel totalScoreLabel;
    private javax.swing.JScrollPane essayScrollPane;
    private javax.swing.JTextArea essayTextArea;
    private javax.swing.JTextField lengthScoreTextField;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JLabel locationConstraintScore;
    private javax.swing.JTextField locationConstraintTextField;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel quasiEnglishLabel;
    private javax.swing.JTextField scoreTextField;
    private javax.swing.JLabel storySequenceLabel;
    private javax.swing.JScrollPane storySequenceScrollPane;
    private javax.swing.JTextArea storySequenceTextArea;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   
}
