/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.LinkedList;
import java.util.List;

import org.apache.commons.math3.analysis.function.Gaussian;

import generator.Parameter;
import others.StoryRecord;

/**
 *
 * @author liqimou
 */
public class TwoCharacterStoryShowingWindow extends javax.swing.JFrame {

    /**
     * Creates new form StoryShowWindow
     */
    public TwoCharacterStoryShowingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreTextField = new javax.swing.JTextField();
        lengthLabel = new javax.swing.JLabel();
        lengthTextField1 = new javax.swing.JTextField();
        lengthScoreTextField1 = new javax.swing.JTextField();
        Slash1 = new javax.swing.JLabel();
        lengthTextField2 = new javax.swing.JTextField();
        lengthScoreTextField2 = new javax.swing.JTextField();
        PNConstraintLabel = new javax.swing.JLabel();
        PNConstraintTextField = new javax.swing.JTextField();
        PNConstraintScoreTextField1 = new javax.swing.JTextField();
        Slash2 = new javax.swing.JLabel();
        PNConstraintScoreTextField2 = new javax.swing.JTextField();
        LocationConstraintLabel = new javax.swing.JLabel();
        LocConstraintScoreTextField1 = new javax.swing.JTextField();
        Slash3 = new javax.swing.JLabel();
        LocConstraintScoreTextField2 = new javax.swing.JTextField();
        c1StorySequenceLabel = new javax.swing.JLabel();
        storySequenceScrollPane1 = new javax.swing.JScrollPane();
        storySequenceTextArea1 = new javax.swing.JTextArea();
        c2StorySequenceLabel = new javax.swing.JLabel();
        storySequenceScrollPane = new javax.swing.JScrollPane();
        storySequenceTextArea2 = new javax.swing.JTextArea();
        quasiEnglishLabel = new javax.swing.JLabel();
        essayScrollPane = new javax.swing.JScrollPane();
        essayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setText("Story");

        scoreLabel.setText("Total Score :");

        scoreTextField.setEditable(false);
        scoreTextField.setText("TOTAL SCORE");

        lengthLabel.setText("Length & Score :");

        lengthTextField1.setEditable(false);
        lengthTextField1.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory().size()+"");
        
        Parameter.gaussianDistribution = new Gaussian(Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength, Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength / 3);
        lengthScoreTextField1.setEditable(false);
        lengthScoreTextField1.setText(Parameter.decimalFormat.format(Parameter.lengthModel.getValue(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory().size(), Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength))+"");

        Slash1.setText("/");

        lengthTextField2.setEditable(false);
        lengthTextField2.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c2StoryList.get(Parameter.selectStoryResultIndex).getStory().size()+"");

        lengthScoreTextField2.setEditable(false);
        lengthScoreTextField2.setText(Parameter.decimalFormat.format(Parameter.lengthModel.getValue(Parameter.storyInformation.get(Parameter.selectStoryIndex).c2StoryList.get(Parameter.selectStoryResultIndex).getStory().size(), Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.storylength))+"");

        List <String> c1List = new LinkedList<String>();
		for (StoryRecord k : Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StoryList.get(Parameter.selectStoryResultIndex).getStory()) {
			c1List.add(k.getConcept());
		}
		List <String> c2List = new LinkedList<String>();
		for (StoryRecord k : Parameter.storyInformation.get(Parameter.selectStoryIndex).c2StoryList.get(Parameter.selectStoryResultIndex).getStory()) {
			c2List.add(k.getConcept());
		}
        
        PNConstraintLabel.setText("P/N Constraint & Score :");

        PNConstraintTextField.setEditable(false);
        PNConstraintTextField.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.positiveConstraintString+"/"
        		+ Parameter.storyInformation.get(Parameter.selectStoryIndex).storyformat.negativeConstraintString);

        PNConstraintScoreTextField1.setEditable(false);
        PNConstraintScoreTextField1.setText(Parameter.decimalFormat.format(Parameter.constraintModel.getValue(c1List, Parameter.selectStoryIndex))+"");

        Slash2.setText("/");

        PNConstraintScoreTextField2.setEditable(false);
        PNConstraintScoreTextField2.setText(Parameter.decimalFormat.format(Parameter.constraintModel.getValue(c2List, Parameter.selectStoryIndex))+"");

        LocationConstraintLabel.setText("Loc Constraint & Score :");

        LocConstraintScoreTextField1.setEditable(false);
        LocConstraintScoreTextField1.setText(Parameter.decimalFormat.format(Parameter.locationConstraintModel.getValue(c1List))+"");

        Slash3.setText("/");

        LocConstraintScoreTextField2.setEditable(false);
        LocConstraintScoreTextField2.setText(Parameter.decimalFormat.format(Parameter.locationConstraintModel.getValue(c2List))+"");
        
        c1StorySequenceLabel.setText("Character 1 Story Sequence");

        storySequenceTextArea1.setEditable(false);
        storySequenceTextArea1.setColumns(20);
        storySequenceTextArea1.setLineWrap(true);
        storySequenceTextArea1.setRows(5);
        storySequenceTextArea1.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c1StorySequenceList.get(Parameter.selectStoryResultIndex));
        storySequenceScrollPane1.setViewportView(storySequenceTextArea1);

        c2StorySequenceLabel.setText("Character 2 Story Sequence");

        storySequenceTextArea2.setEditable(false);
        storySequenceTextArea2.setColumns(20);
        storySequenceTextArea2.setLineWrap(true);
        storySequenceTextArea2.setRows(5);
        storySequenceTextArea2.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).c2StorySequenceList.get(Parameter.selectStoryResultIndex));
        storySequenceScrollPane.setViewportView(storySequenceTextArea2);

        quasiEnglishLabel.setText("Quasi-English Story");

        essayTextArea.setEditable(false);
        essayTextArea.setColumns(20);
        essayTextArea.setLineWrap(true);
        essayTextArea.setRows(5);
        essayTextArea.setText(Parameter.storyInformation.get(Parameter.selectStoryIndex).essayList.get(Parameter.selectStoryResultIndex));
        essayScrollPane.setViewportView(essayTextArea);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addComponent(essayScrollPane)
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(storySequenceScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(storySequenceScrollPane1))
                        .addContainerGap())
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PNConstraintLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LocationConstraintLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lengthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(lengthScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Slash1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lengthScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addComponent(PNConstraintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PNConstraintScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Slash2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PNConstraintScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(scoreTextField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(c1StorySequenceLabel)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(LocConstraintScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Slash3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LocConstraintScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 5, Short.MAX_VALUE))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(quasiEnglishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(c2StorySequenceLabel)
                        .addGap(211, 211, 211))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthLabel)
                    .addComponent(lengthTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slash1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNConstraintTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNConstraintLabel)
                    .addComponent(PNConstraintScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNConstraintScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slash2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LocConstraintScoreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationConstraintLabel)
                    .addComponent(LocConstraintScoreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Slash3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c1StorySequenceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storySequenceScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(c2StorySequenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storySequenceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quasiEnglishLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(essayScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public void openWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwoCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwoCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwoCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwoCharacterStoryShowingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwoCharacterStoryShowingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField LocConstraintScoreTextField1;
    private javax.swing.JTextField LocConstraintScoreTextField2;
    private javax.swing.JLabel LocationConstraintLabel;
    private javax.swing.JLabel PNConstraintLabel;
    private javax.swing.JTextField PNConstraintScoreTextField1;
    private javax.swing.JTextField PNConstraintScoreTextField2;
    private javax.swing.JTextField PNConstraintTextField;
    private javax.swing.JLabel Slash1;
    private javax.swing.JLabel Slash2;
    private javax.swing.JLabel Slash3;
    private javax.swing.JLabel c1StorySequenceLabel;
    private javax.swing.JLabel c2StorySequenceLabel;
    private javax.swing.JScrollPane essayScrollPane;
    private javax.swing.JTextArea essayTextArea;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthScoreTextField1;
    private javax.swing.JTextField lengthScoreTextField2;
    private javax.swing.JTextField lengthTextField1;
    private javax.swing.JTextField lengthTextField2;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel quasiEnglishLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JTextField scoreTextField;
    private javax.swing.JScrollPane storySequenceScrollPane;
    private javax.swing.JScrollPane storySequenceScrollPane1;
    private javax.swing.JTextArea storySequenceTextArea1;
    private javax.swing.JTextArea storySequenceTextArea2;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration                   
}
